Add missing packages to requirements.txt
JonathanVusich/pcpartpicker-scraper pull request #1
Opened 2019-07-12 21:33 UTC by damageboy

Missing pacages...

2019-07-13 19:41 UTC, JonathanVusich requested changes
It would probably actually be best to remove the `publish` method in `main.py`. That was just something that I was experimenting with, and wasn't really intended to make it into production. In reality, updates to the database should be done through a PR and not just pushing directly to master. That way we can avoid the `sh` requirement as well. Would you mind making these changes? Otherwise it's looking good!

Edit: I have added CI and tests as well to this repo. Perhaps you should pull those changes and integrate them as well.

2019-07-14 06:03 UTC, damageboy commented
Sure thing...

2019-07-14 09:36 UTC, damageboy commented
I think I've addressed your request, but I can't mark anything as resolved since I rebased the whole thing on top of master...

Let me know if you're good with it.

I'd love to rebase my other thing (with ecc + parallelism support) and submit a pull request for that as well, I'd just want to get this silly thing out of the way...

2019-07-14 18:10 UTC, JonathanVusich approved these changes

2019-07-14 18:11 UTC, merged